/* Generated By:JavaCC: Do not edit this line. MyBasicConstants.java */
package edu.itsco;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyBasicConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO = 5;
  /** RegularExpression Id. */
  int FIN = 6;
  /** RegularExpression Id. */
  int VAR = 7;
  /** RegularExpression Id. */
  int ENTERO = 8;
  /** RegularExpression Id. */
  int DECIMAL = 9;
  /** RegularExpression Id. */
  int CADENA = 10;
  /** RegularExpression Id. */
  int IMPRIMIR = 11;
  /** RegularExpression Id. */
  int LEER = 12;
  /** RegularExpression Id. */
  int SI = 13;
  /** RegularExpression Id. */
  int ENTONCES = 14;
  /** RegularExpression Id. */
  int SINO = 15;
  /** RegularExpression Id. */
  int SELECCIONA = 16;
  /** RegularExpression Id. */
  int CASO = 17;
  /** RegularExpression Id. */
  int ROMPE = 18;
  /** RegularExpression Id. */
  int DESDE = 19;
  /** RegularExpression Id. */
  int HASTA = 20;
  /** RegularExpression Id. */
  int SIGUIENTE = 21;
  /** RegularExpression Id. */
  int MIENTRAS = 22;
  /** RegularExpression Id. */
  int HACER = 23;
  /** RegularExpression Id. */
  int FUNCION = 24;
  /** RegularExpression Id. */
  int REGRESA = 25;
  /** RegularExpression Id. */
  int SUMA = 26;
  /** RegularExpression Id. */
  int RESTA = 27;
  /** RegularExpression Id. */
  int MULTI = 28;
  /** RegularExpression Id. */
  int DIV = 29;
  /** RegularExpression Id. */
  int IGUAL = 30;
  /** RegularExpression Id. */
  int MAYOR = 31;
  /** RegularExpression Id. */
  int MENOR = 32;
  /** RegularExpression Id. */
  int AND = 33;
  /** RegularExpression Id. */
  int OR = 34;
  /** RegularExpression Id. */
  int NOT = 35;
  /** RegularExpression Id. */
  int AP = 36;
  /** RegularExpression Id. */
  int CP = 37;
  /** RegularExpression Id. */
  int DP = 38;
  /** RegularExpression Id. */
  int AC = 39;
  /** RegularExpression Id. */
  int CC = 40;
  /** RegularExpression Id. */
  int COMA = 41;
  /** RegularExpression Id. */
  int digito = 42;
  /** RegularExpression Id. */
  int letra = 43;
  /** RegularExpression Id. */
  int ID = 44;
  /** RegularExpression Id. */
  int VALOR_ENTERO = 45;
  /** RegularExpression Id. */
  int VALOR_DECIMAL = 46;
  /** RegularExpression Id. */
  int VALOR_CADENA = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"inicio\"",
    "\"fin\"",
    "\"var\"",
    "\"entero\"",
    "\"decimal\"",
    "\"cadena\"",
    "\"imprimir\"",
    "\"leer\"",
    "\"si\"",
    "\"entonces\"",
    "\"sino\"",
    "\"selecciona\"",
    "\"caso\"",
    "\"rompe\"",
    "\"desde\"",
    "\"hasta\"",
    "\"siguiente\"",
    "\"mientras\"",
    "\"hacer\"",
    "\"funcion\"",
    "\"regresa\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "<digito>",
    "<letra>",
    "<ID>",
    "<VALOR_ENTERO>",
    "<VALOR_DECIMAL>",
    "<VALOR_CADENA>",
  };

}
